import { createJiti } from "jiti";
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import ts from "typescript";
import {
  CODEGEN_REGISTRY_FILE,
  GITIGNORE_FILE,
  LEADING_WHITESPACE_PATTERN,
  OUTPUT_CONFIGS_FILE,
  OUTPUT_FILE,
  PLUGINS_DIR,
  STEP_REGISTRY_FILE,
  SYSTEM_INTEGRATION_TYPES,
  TYPES_FILE,
} from "../server/constants";
import { computeActionId, getAllIntegrations, getIntegrationTypes } from "./index";
import { StepFileAnalysis } from "./types";

/**
 * Format TypeScript code using Prettier
 */
async function formatCode(code: string): Promise<string> {
  try {
    const prettier = await import("prettier");
    return await prettier.format(code, { parser: "typescript" });
  } catch (error) {
    console.warn("   Warning: Failed to format generated code:", error);
    return code;
  }
}

// Track generated codegen templates
const generatedCodegenTemplates = new Map<
  string,
  { template: string; integrationType: string }
>();

/**
 * Generate the plugins/index.ts file
 */
function generateIndexFile(plugins: string[]): void {
  const imports = plugins.map((plugin) => `import "./${ plugin }";`).join("\n");

  const content = `/**
 * Plugins Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To add a new integration:
 * 1. Create a new directory in plugins/ (e.g., plugins/my-integration/)
 * 2. Add your plugin files (index.tsx, steps/, codegen/, etc.)
 * 3. Run: pnpm discover-plugins (or it runs automatically on build)
 *
 * To remove an integration:
 * 1. Delete the plugin directory
 * 2. Run: pnpm discover-plugins (or it runs automatically on build)
 */

// Side-effect imports: each plugin calls registerIntegration() on import
${ imports || "// No plugins discovered" }

// Re-export registry utilities so consuming apps can import from "@/plugins"
export {
  computeActionId,
  findActionById,
  flattenConfigFields,
  generateAIActionPrompts,
  getActionsByCategory,
  getAllActions,
  getAllDependencies,
  getAllEnvVars,
  getAllIntegrations,
  getCredentialMapping,
  getDependenciesForActions,
  getIntegration,
  getIntegrationLabels,
  getIntegrationTypes,
  getPluginEnvVars,
  getSortedIntegrationTypes,
  isFieldGroup,
  parseActionId,
  registerIntegration,
} from "next-workflow-builder/plugins";

export type {
  ActionConfigField,
  ActionConfigFieldBase,
  ActionConfigFieldGroup,
  ActionWithFullId,
  IntegrationPlugin,
  PluginAction,
} from "next-workflow-builder/plugins";
`;

  writeFileSync(OUTPUT_FILE, content, "utf-8");
}

/**
 * Generate the lib/types/integration.ts file with dynamic types
 */
async function generateTypesFile(): Promise<void> {
  // Ensure the types directory exists
  const typesDir = dirname(TYPES_FILE);
  if (!existsSync(typesDir)) {
    mkdirSync(typesDir, { recursive: true });
  }

  // Get plugin types from registry
  const pluginTypes = getIntegrationTypes();

  // Combine plugin types with system types
  const allTypes = [...pluginTypes, ...SYSTEM_INTEGRATION_TYPES].sort();

  // Generate the union type
  const unionType = allTypes.map((t) => `  | "${ t }"`).join("\n");

  const content = `/**
 * Integration Types (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To add a new integration type:
 * 1. Create a plugin in plugins/ directory, OR
 * 2. Add a system integration to SYSTEM_INTEGRATION_TYPES in discover-plugins.ts
 * 3. Run: pnpm discover-plugins
 *
 * Generated types: ${ allTypes.join(", ") }
 */

// Integration type union - plugins + system integrations
export type IntegrationType =
${ unionType };

// Generic config type - plugins define their own keys via formFields[].configKey
export type IntegrationConfig = Record<string, string | undefined>;
`;

  writeFileSync(TYPES_FILE, content, "utf-8");
  console.log(
    `Generated lib/types/integration.ts with ${ allTypes.length } type(s)`,
  );
}

/**
 * Generate the lib/codegen-registry.ts file with auto-generated templates
 */
function generateCodegenRegistry(): void {
  const entries = Array.from(generatedCodegenTemplates.entries());

  if (entries.length === 0) {
    console.log("No codegen templates generated");
    return;
  }

  // Generate template string literals
  const templateEntries = entries
    .map(([actionId, { template }]) => {
      // Escape backticks and ${} in the template for safe embedding
      const escapedTemplate = template
        .replace(/\\/g, "\\\\")
        .replace(/`/g, "\\`")
        .replace(/\$\{/g, "\\${");
      return `  "${ actionId }": \`${ escapedTemplate }\`,`;
    })
    .join("\n\n");

  const content = `/**
 * Codegen Registry (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Contains auto-generated codegen templates for steps with stepHandler.
 * These templates are used when exporting workflows to standalone projects.
 *
 * Generated templates: ${ entries.length }
 */

/**
 * Auto-generated codegen templates
 * Maps action IDs to their generated export code templates
 */
export const AUTO_GENERATED_TEMPLATES: Record<string, string> = {
${ templateEntries }
};

/**
 * Get the auto-generated codegen template for an action
 */
export function getAutoGeneratedTemplate(actionId: string): string | undefined {
  return AUTO_GENERATED_TEMPLATES[actionId];
}
`;

  writeFileSync(CODEGEN_REGISTRY_FILE, content, "utf-8");
  console.log(
    `Generated lib/codegen-registry.ts with ${ entries.length } template(s)`,
  );
}

// ============================================================================
// Step Registry Generation
// ============================================================================

/**
 * Generate the lib/step-registry.ts file with step import functions
 * This enables dynamic imports that are statically analyzable by the bundler
 */
async function generateStepRegistry(): Promise<void> {
  const integrations = getAllIntegrations();

  // Collect all action -> step mappings
  const stepEntries: Array<{
    actionId: string;
    label: string;
    integration: string;
    stepImportPath: string;
    stepFunction: string;
  }> = [];

  for (const integration of integrations) {
    for (const action of integration.actions) {
      const fullActionId = computeActionId(integration.type, action.slug);
      stepEntries.push({
        actionId: fullActionId,
        label: action.label,
        integration: integration.type,
        stepImportPath: action.stepImportPath,
        stepFunction: action.stepFunction,
      });
    }
  }

  // Generate the step importer map with static imports
  // Include both namespaced IDs and legacy label-based IDs for backward compatibility
  const importerEntries = stepEntries
    .flatMap(({ actionId, integration, stepImportPath, stepFunction }) => {
      return [
        `  "${ actionId }": {
    importer: () => import("@/plugins/${ integration }/steps/${ stepImportPath }"),
    stepFunction: "${ stepFunction }",
  },`,
      ];
    })
    .join("\n");

  // Generate the action labels map for displaying human-readable names
  const labelEntries = stepEntries
    .map(({ actionId, label }) => `  "${ actionId }": "${ label }",`)
    .join("\n");

  const content = `/**
 * Step Registry (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * This registry enables dynamic step imports that are statically analyzable
 * by the bundler. Each action type maps to its step importer function.
 *
 * Generated entries: ${ stepEntries.length }
 */

// biome-ignore lint/suspicious/noExplicitAny: Dynamic step module types - step functions take any input
export type StepFunction = (input: any) => Promise<any>;

// Step modules may contain the step function plus other exports (types, constants, etc.)
// biome-ignore lint/suspicious/noExplicitAny: Dynamic module with mixed exports
export type StepModule = Record<string, any>;

export type StepImporter = {
  importer: () => Promise<StepModule>;
  stepFunction: string;
};

/**
 * Plugin step importers - maps action types to their step import functions
 * These imports are statically analyzable by the bundler
 */
export const PLUGIN_STEP_IMPORTERS: Record<string, StepImporter> = {
${ importerEntries }
};

/**
 * Action labels - maps action IDs to human-readable labels
 * Used for displaying friendly names in the UI (e.g., Runs tab)
 */
export const ACTION_LABELS: Record<string, string> = {
${ labelEntries }
};

/**
 * Get a step importer for an action type
 */
export function getStepImporter(actionType: string): StepImporter | undefined {
  return PLUGIN_STEP_IMPORTERS[actionType];
}

/**
 * Get the human-readable label for an action type
 */
export function getActionLabel(actionType: string): string | undefined {
  return ACTION_LABELS[actionType];
}
`;

  writeFileSync(STEP_REGISTRY_FILE, content, "utf-8");
  console.log(
    `Generated lib/step-registry.ts with ${ stepEntries.length } step(s)`,
  );
}

/**
 * Generate the lib/output-display-configs.ts file (client-safe)
 * This file can be imported in client components
 */
async function generateOutputDisplayConfigs(): Promise<void> {
  const integrations = getAllIntegrations();

  // Collect output configs (only built-in types, not component types)
  const outputConfigs: Array<{
    actionId: string;
    type: string;
    field: string;
  }> = [];

  for (const integration of integrations) {
    for (const action of integration.actions) {
      // Only include built-in config types (image/video/url), not component types
      if (action.outputConfig && action.outputConfig.type !== "component") {
        outputConfigs.push({
          actionId: computeActionId(integration.type, action.slug),
          type: action.outputConfig.type,
          field: action.outputConfig.field,
        });
      }
    }
  }

  // Generate output config entries
  const outputConfigEntries = outputConfigs
    .map(
      ({ actionId, type, field }) =>
        `  "${ actionId }": { type: "${ type }", field: "${ field }" },`,
    )
    .join("\n");

  const content = `/**
 * Output Display Configs (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * This file is CLIENT-SAFE and can be imported in client components.
 * It maps action IDs to their output display configuration.
 *
 * Generated configs: ${ outputConfigs.length }
 */

export type OutputDisplayConfig = {
  type: "image" | "video" | "url";
  field: string;
};

/**
 * Output display configs - maps action IDs to their display configuration
 * Used for rendering outputs in the workflow runs panel
 */
export const OUTPUT_DISPLAY_CONFIGS: Record<string, OutputDisplayConfig> = {
${ outputConfigEntries }
};

/**
 * Get the output display config for an action type
 */
export function getOutputDisplayConfig(actionType: string): OutputDisplayConfig | undefined {
  return OUTPUT_DISPLAY_CONFIGS[actionType];
}
`;

  writeFileSync(OUTPUT_CONFIGS_FILE, content, "utf-8");
  console.log(
    `Generated lib/output-display-configs.ts with ${ outputConfigs.length } config(s)`,
  );
}

/** Check if an import should be included in exports */
function shouldIncludeImport(moduleSpec: string, importText: string): boolean {
  // Skip internal imports
  if (moduleSpec.startsWith("@/") || moduleSpec.startsWith(".")) {
    return false;
  }
  // Skip server-only import
  if (importText.includes("server-only")) {
    return false;
  }
  return true;
}

/** Extract function info from a function declaration */
function extractFunctionInfo(
  node: ts.FunctionDeclaration,
  sourceCode: string,
): StepFileAnalysis["coreFunction"] {
  if (!(node.name && node.body)) {
    return null;
  }

  const params = node.parameters
    .map((p) => sourceCode.slice(p.pos, p.end).trim())
    .join(", ");

  const returnType = node.type
    ? sourceCode.slice(node.type.pos, node.type.end).trim()
    : "Promise<unknown>";

  const body = sourceCode.slice(node.body.pos, node.body.end).trim();

  return {
    name: node.name.text,
    params,
    returnType,
    body,
  };
}

/** Create empty analysis result */
function createEmptyAnalysis(): StepFileAnalysis {
  return {
    hasExportCore: false,
    integrationType: null,
    coreFunction: null,
    inputTypes: [],
    imports: [],
  };
}

/** Process exported variable declarations */
function processExportedVariable(
  decl: ts.VariableDeclaration,
  result: StepFileAnalysis,
): void {
  if (!ts.isIdentifier(decl.name)) {
    return;
  }

  const name = decl.name.text;
  const init = decl.initializer;

  if (name === "_integrationType" && init && ts.isStringLiteral(init)) {
    result.integrationType = init.text;
  }
}

/** Process variable statement node */
function processVariableStatement(
  node: ts.VariableStatement,
  result: StepFileAnalysis,
): void {
  const isExported = node.modifiers?.some(
    (m) => m.kind === ts.SyntaxKind.ExportKeyword,
  );
  if (!isExported) {
    return;
  }

  for (const decl of node.declarationList.declarations) {
    processExportedVariable(decl, result);
  }
}


/** Check if a type name should be included in exports */
function shouldIncludeType(typeName: string): boolean {
  return (
    typeName.endsWith("Result") ||
    typeName.endsWith("Credentials") ||
    typeName.endsWith("CoreInput")
  );
}

/** Process type alias node */
function processTypeAlias(
  node: ts.TypeAliasDeclaration,
  sourceCode: string,
  result: StepFileAnalysis,
): void {
  if (shouldIncludeType(node.name.text)) {
    result.inputTypes.push(sourceCode.slice(node.pos, node.end).trim());
  }
}

/** Process import declaration node */
function processImportDeclaration(
  node: ts.ImportDeclaration,
  sourceCode: string,
  result: StepFileAnalysis,
): void {
  const spec = node.moduleSpecifier;
  if (!ts.isStringLiteral(spec)) {
    return;
  }
  const importText = sourceCode.slice(node.pos, node.end).trim();
  if (shouldIncludeImport(spec.text, importText)) {
    result.imports.push(importText);
  }
}

/** Process a single AST node for exports, types, and imports */
function processNode(
  node: ts.Node,
  sourceCode: string,
  result: StepFileAnalysis,
): void {
  if (ts.isVariableStatement(node)) {
    processVariableStatement(node, result);
    return;
  }

  if (ts.isTypeAliasDeclaration(node)) {
    processTypeAlias(node, sourceCode, result);
    return;
  }

  if (ts.isImportDeclaration(node)) {
    processImportDeclaration(node, sourceCode, result);
    return;
  }

  // Check for stepHandler function (doesn't need to be exported)
  if (ts.isFunctionDeclaration(node) && node.name?.text === "stepHandler") {
    result.hasExportCore = true;
    result.coreFunction = extractFunctionInfo(node, sourceCode);
  }
}

/**
 * Extract information about a step file's exports using TypeScript AST
 */
function analyzeStepFile(filePath: string): StepFileAnalysis {
  const result = createEmptyAnalysis();

  if (!existsSync(filePath)) {
    return result;
  }

  const sourceCode = readFileSync(filePath, "utf-8");
  const sourceFile = ts.createSourceFile(
    filePath,
    sourceCode,
    ts.ScriptTarget.Latest,
    true,
  );

  // Single pass: find stepHandler function, types, and imports
  ts.forEachChild(sourceFile, (node) => {
    processNode(node, sourceCode, result);
  });

  return result;
}

/**
 * Generate a codegen template from a step file's core function
 */
async function generateCodegenTemplate(
  stepFilePath: string,
  stepFunctionName: string,
): Promise<string | null> {
  const analysis = analyzeStepFile(stepFilePath);

  if (!(analysis.hasExportCore && analysis.coreFunction)) {
    return null;
  }

  const { coreFunction, integrationType, inputTypes, imports } = analysis;

  // Extract the inner body (remove outer braces)
  let innerBody = coreFunction.body.trim();
  if (innerBody.startsWith("{")) {
    innerBody = innerBody.slice(1);
  }
  if (innerBody.endsWith("}")) {
    innerBody = innerBody.slice(0, -1);
  }
  innerBody = innerBody.trim();

  // Extract input type from first parameter
  const inputType =
    coreFunction.params
      .split(",")[0]
      .replace(LEADING_WHITESPACE_PATTERN, "")
      .split(":")[1]
      ?.trim() || "unknown";

  // Build the raw template (formatter will fix indentation)
  const rawTemplate = `${ imports.join("\n") }
import { fetchCredentials } from './lib/credential-helper';

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  return String(error);
}

${ inputTypes.join("\n\n") }

export async function ${ stepFunctionName }(input: ${ inputType }): ${ coreFunction.returnType } {
  "use step";
  const credentials = await fetchCredentials("${ integrationType || "unknown" }");
${ innerBody }
}`;

  // Format the generated code
  return await formatCode(rawTemplate);
}

/**
 * Process step files and generate codegen templates
 */
async function processStepFilesForCodegen(): Promise<void> {
  const integrations = getAllIntegrations();

  for (const integration of integrations) {
    for (const action of integration.actions) {
      const stepFilePath = join(
        PLUGINS_DIR,
        integration.type,
        "steps",
        `${ action.stepImportPath }.ts`,
      );

      const template = await generateCodegenTemplate(
        stepFilePath,
        action.stepFunction,
      );

      if (template) {
        const actionId = computeActionId(integration.type, action.slug);
        generatedCodegenTemplates.set(actionId, {
          template,
          integrationType: integration.type,
        });
        console.log(`   Generated codegen template for ${ actionId }`);
      }
    }
  }
}

/**
 * Ensure generated files are listed in the consumer's .gitignore
 * (it's auto-generated and should not be committed).
 */
function ensureGitignore(): void {
  const SECTION_HEADER = "\n# Auto-generated by discover-plugins";

  // Collect all absolute paths we want to ignore
  // Note: OUTPUT_FILE (plugins/index.ts) is excluded — it's user-managed and should be committed
  const filesToIgnore = [
    TYPES_FILE,
    CODEGEN_REGISTRY_FILE,
    STEP_REGISTRY_FILE,
    OUTPUT_CONFIGS_FILE,
    OUTPUT_FILE,
  ];

  // Convert to relative paths
  const relativePaths = filesToIgnore.map((file) => relative(process.cwd(), file));

  let content = "";
  if (existsSync(GITIGNORE_FILE)) {
    content = readFileSync(GITIGNORE_FILE, "utf-8");
  }

  const existingLines = new Set(content.split("\n").map((line) => line.trim()));
  const newEntries = relativePaths.filter((entry) => !existingLines.has(entry));

  if (newEntries.length > 0) {
    let textToAppend = "";

    // 1. Ensure we start on a new line if the file doesn't end with one
    if (content.length > 0 && !content.endsWith("\n")) {
      textToAppend += "\n";
    }

    // 2. Add the comment only if it doesn't exist yet
    if (!content.includes(SECTION_HEADER)) {
      textToAppend += `${ SECTION_HEADER }\n`;
    }

    // 3. Add the new files
    textToAppend += newEntries.join("\n") + "\n";

    writeFileSync(GITIGNORE_FILE, content + textToAppend, "utf-8");
    console.log(`Updated .gitignore with ${ newEntries.length } new file(s).`);
  }
}

/**
 * Main execution
 */
async function discoverPlugins() {
  console.log("Discovering plugins...");

  // Discover all plugin directories
  const entries = readdirSync(PLUGINS_DIR);
  const plugins = entries.filter((entry) => {
    // Skip special directories and files
    if (
      entry.startsWith("_") ||
      entry.startsWith(".") ||
      entry === "index.ts" ||
      entry === "registry.ts"
    ) {
      return false;
    }

    // Only include directories
    const fullPath = join(PLUGINS_DIR, entry);
    try {
      return statSync(fullPath).isDirectory();
    } catch {
      return false;
    }
  }).sort();

  // Dump plugins to console
  if (plugins.length === 0) {
    console.log("No plugins found in plugins/ directory");
  } else {
    console.log(`Found ${ plugins.length } plugin(s):`);
    for (const plugin of plugins) {
      console.log(`   - ${ plugin }`);
    }
  }

  // Ensure auto-generated files are gitignored
  ensureGitignore();

  console.log("Generating plugins/index.ts...");
  generateIndexFile(plugins);

  // Import each plugin to trigger registerIntegration() calls
  // This populates the integrationRegistry before generating registry files
  if (plugins.length > 0) {
    console.log("Registering plugins...\n");
    const jiti = createJiti(import.meta.url, { jsx: true });
    for (const plugin of plugins) {
      try {
        await jiti.import(join(PLUGINS_DIR, plugin));
        console.log(`   Registered: ${ plugin }`);
      } catch (error) {
        console.warn(`   Warning: Failed to import plugin ${ plugin }:`, error);
      }
    }
  }

  console.log("Generating lib/types/integration.ts...");
  await generateTypesFile();

  console.log("Generating lib/step-registry.ts...");
  await generateStepRegistry();

  console.log("Generating lib/output-display-configs.ts...");
  await generateOutputDisplayConfigs();

  console.log("\nProcessing step files for codegen templates...");
  await processStepFilesForCodegen();

  console.log("Generating lib/codegen-registry.ts...");
  generateCodegenRegistry();

  console.log("Done! Plugin registry updated.\n");
}

export { discoverPlugins };
